// <auto-generated />
using System;
using DinDinSpinWeb.Infra.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DinDinSpinWeb.Migrations
{
    [DbContext(typeof(DinDinSpinDbContext))]
    partial class DinDinSpinDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DinDinSpin.Domain.Models.Dinner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("MainIngredientId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<DateTime>("RegisterDate");

                    b.Property<Guid>("SpinnerId");

                    b.HasKey("Id");

                    b.HasIndex("MainIngredientId");

                    b.HasIndex("SpinnerId");

                    b.ToTable("Dinners");
                });

            modelBuilder.Entity("DinDinSpin.Domain.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<bool>("PlantBased");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("DinDinSpin.Domain.Models.Spinner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Spinners");
                });

            modelBuilder.Entity("DinDinSpin.Domain.Models.Dinner", b =>
                {
                    b.HasOne("DinDinSpin.Domain.Models.Ingredient", "MainIngredient")
                        .WithMany()
                        .HasForeignKey("MainIngredientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DinDinSpin.Domain.Models.Spinner", "Spinner")
                        .WithMany("Dinners")
                        .HasForeignKey("SpinnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
